FROM node:22-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps/end-user ./apps
COPY packages ./packages

RUN npm install

RUN npm run db:generate

RUN npm run build

CMD [ "npm", "run", "start" ]