name: Deploy End User App

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/end-user/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Push New Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.enduser
          push: true
          tags: easc01/ewallet-enduser:latest

      - name: Verify Pushed Image
        run: docker pull easc01/ewallet-enduser:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_KEY }}
            sudo docker pull easc01/ewallet-enduser:latest
            
            sudo docker stop enduser-container || true
            sudo docker rm enduser-container || true
            
            sudo docker run -d \
              --name enduser-container \
              --restart=unless-stopped \
              -p ${{ vars.END_USER_APP_PORT }}:${{ vars.END_USER_APP_PORT }} \
              -e END_USER_BASE_URL=${{ vars.END_USER_BASE_URL }} \
              -e BANK_WEBHOOK_BASE_URL=${{ vars.BANK_WEBHOOK_BASE_URL }} \
              -e BANK_MOCK_BASE_URL=${{ vars.BANK_MOCK_BASE_URL }} \
              -e BANK_INTERFACE_BASE_URL=${{ vars.BANK_INTERFACE_BASE_URL }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e PORT=${{ vars.END_USER_APP_PORT }} \
              -e NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e GOOGLE_ID=${{ secrets.GOOGLE_ID }} \
              -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
              easc01/ewallet-enduser:latest
