name: Deploy Bank Webhook

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/bank-webhook/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Push New Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bankwebhook
          push: true
          tags: easc01/ewallet-bankwebhook:latest

      - name: Verify Pushed Image
        run: docker pull easc01/ewallet-bankwebhook:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull easc01/ewallet-bankwebhook:latest
            
            sudo docker stop bankwebhook-container || true
            sudo docker rm bankwebhook-container || true
            
            sudo docker run -d \
              --name bankwebhook-container \
              --restart=unless-stopped \
              -p ${{ vars.BANK_WEBHOOK_APP_PORT }}:${{ vars.BANK_WEBHOOK_APP_PORT }} \
              -e END_USER_BASE_URL=${{ vars.END_USER_BASE_URL }} \
              -e BANK_WEBHOOK_BASE_URL=${{ vars.BANK_WEBHOOK_BASE_URL }} \
              -e BANK_MOCK_BASE_URL=${{ vars.BANK_MOCK_BASE_URL }} \
              -e BANK_INTERFACE_BASE_URL=${{ vars.BANK_INTERFACE_BASE_URL }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e PORT=${{ vars.BANK_WEBHOOK_APP_PORT }} \
              easc01/ewallet-bankwebhook:latest
